#!/usr/bin/env bash
# sync.sh — pull my CURRENT configs off this box back into the repo, scrubbed.
# This is how mydotfiles periodically absorbs whatever I've tweaked. It:
#   1. copies live dotfiles through the secret redactor into dotfiles/
#   2. regenerates the skill catalog (from ~/.claude/skills + ~/.codex/skills) between markers in README.md
#   3. runs the hard secret scan and ABORTS if anything leaks
#   4. stages changes — but does NOT commit or push (that's your call)
#
# Run manually (`make sync`) or on a schedule (see launchd/). Never auto-pushes.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
D="$REPO/dotfiles"
SCRUB="$REPO/scripts/scrub.sh"

copy() { # copy <live> <repo-relative-dest>
  local live="$1" dest="$D/$2"
  [ -f "$live" ] || { echo "skip (missing): $live"; return; }
  mkdir -p "$(dirname "$dest")"
  "$SCRUB" redact < "$live" > "$dest"
  echo "synced $live -> ${dest#$REPO/}"
}

# --- 1. clean dotfiles (no secrets in these; redactor is a safety net) ---
copy "$HOME/.tmux.conf"                 "tmux.conf"
copy "$HOME/.vimrc"                     "vimrc"
copy "$HOME/.gitignore_global"          "gitignore_global"
copy "$HOME/.config/tmux/git-status.sh" "config-tmux/git-status.sh"
chmod +x "$D/config-tmux/git-status.sh" 2>/dev/null || true
# NOTE: ~/.zshrc and ~/.gitconfig are NOT synced raw — they hold secrets/identity.
#       Curate dotfiles/zshrc.snippets and dotfiles/gitconfig.template by hand.

# --- 2. regenerate the skill catalog between markers in README.md ---
gen_skills() {
  echo '<!-- SKILLS:BEGIN (auto-generated by scripts/sync.sh — do not edit by hand) -->'
  echo
  echo "Skills currently installed on this box (name — one-line description):"
  echo
  local dir base desc
  for root in "$HOME/.claude/skills" "$HOME/.codex/skills"; do
    [ -d "$root" ] || continue
    echo "**\`~${root#$HOME}\`**"
    echo
    for dir in "$root"/*/; do
      [ -d "$dir" ] || continue
      base="$(basename "$dir")"
      desc=""
      if [ -f "$dir/SKILL.md" ]; then
        desc="$(sed -nE 's/^description:[[:space:]]*//p' "$dir/SKILL.md" | head -1 | sed -E 's/^"//; s/"$//' | cut -c1-140 || true)"
      fi
      if [ -n "$desc" ]; then echo "- \`$base\` — $desc"; else echo "- \`$base\`"; fi
    done
    echo
  done
  echo '<!-- SKILLS:END -->'
}

README="$REPO/README.md"
b="$(grep -n 'SKILLS:BEGIN' "$README" | head -1 | cut -d: -f1 || true)"
e="$(grep -n 'SKILLS:END'   "$README" | head -1 | cut -d: -f1 || true)"
if [ -n "$b" ] && [ -n "$e" ] && [ "$e" -ge "$b" ]; then
  tmp="$(mktemp)"
  head -n "$((b-1))" "$README" >  "$tmp"   # everything before BEGIN
  gen_skills                    >> "$tmp"   # fresh block (emits its own BEGIN/END)
  tail -n "+$((e+1))" "$README" >> "$tmp"   # everything after END
  mv "$tmp" "$README"
  echo "regenerated skill catalog in README.md"
else
  echo "note: no SKILLS markers in README.md — skipped catalog regen"
fi

# --- 3. HARD secret scan (the gate) ---
mapfile -t FILES < <(git -C "$REPO" ls-files; find "$D" -type f)
"$SCRUB" scan "${FILES[@]}" "$README"

# --- 4. stage only; leave commit/push to you ---
git -C "$REPO" add -A
echo
echo "synced + scanned clean. Review with:  git -C $REPO diff --cached"
echo "then commit/push yourself. sync.sh never pushes."
